### ISSUE TITLE
Переход на MyBalance с Excel VBA (пошаговое руководство)

### ISSUE THREAD

**Issue by AlexZibin** [hudyakov74/MyBalance#1]
Здравствуйте!
Пожалуйста, помогите облегчить переход на MyBalance с Excel - может быть, есть какое-то пошаговое руководство по созданию таблиц и их взаимосвязей?
Про lsFusion я узнал неделю назад. 
Попытался освоить, но пока дальше запуска примеров не продвинулся.
Посоветуйте, как начать человеку с богатым опытом Excel VBA, MS Access, C++, Visual Studio Code+PlatformIO (плюс знаю на начальном уровне JS и Python), но без  знания Java и IntelliJ IDEA.
Заранее больше спасибо!

**Comment by hudyakov74** [comment]
Добрый день. 
тут как бы такое дело. 
При замене какой бы то ни было таблицы из экселя у нас есть 3 проблемы
1. Используются некие измерения - справочники.  например список подразделений и статей затрат
2. Заводится структура хранения мер (показателей) в некоей таблице. Например "Затраты подразделений" с мерой "Сумма затрат"
3. Эта самая таблица должна хранится в некоторой  структуре. которая дает такие вещи
 -  например как элемент иерархии вместе с другими таблицами например "выручка", "расчет себестоимости". 
 - можно было сделать еще один "слой" данных в смысле сценария. Например "Сценарий план", "сценарий факт".
 
в свете этих 3 вопросов MyBalance занимается 
1 вопросом - в части метакода по созданию "типового справочника"
3 вопросом - структурой бюджета, сценариями и вызовом отображения конкретной таблицы бюджета  Например "Затраты подразделений".
2 вопрос - по созданию непосредственно объекта моделирующего вашу эксель таблицу непосредственно решается написанием модуля в lsfusion. добавление конкретных справочников - тоже отнесено на уровень настройки.

В принципе все что выложено тут один в один совпадает с тем что я сейчас использую. но ни одного примера конкретного бюджета там нет. я первоначально все выложил и не описывал сути. дайте мне денёк, я выложу пример с одним бюджетом и попробую описать этот момент.

**Comment by AlexZibin** [comment]
> дайте мне денек я выложу пример с одним бюджетом

**Спасибо! 
Буду ждать!**

**Comment by hudyakov74** [comment]
Обновил ядро - по мелочи добавилось. Обновил немного описание. По хорошему надо описать как внешние данные по одата забираю. как отчеты подключаю. А вот расчеты и разные калькуляции между разными таблицами делаются по лекалу команды copy.
Кстати отчеты все делаю в эксель.  
простой отчет добавил для примера - без использования справочника отчетов. если со справочником то еще права можно задавать. Хотя права можно штатными средствами на кнопки задавать.

о типовом использовании экселя для кубов тут написал https://habr.com/ru/post/588268/

**Comment by hudyakov74** [comment]
простой отчет добавил для примера - без использования справочника отчетов. если со справочником то еще права можно задавать.
